# Generated by Django 5.0.4 on 2024-04-27 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('typ', models.CharField(max_length=100)),
                ('rocznik', models.PositiveIntegerField()),
                ('przebieg', models.PositiveIntegerField()),
                ('moc_silnika', models.PositiveIntegerField()),
                ('skrzynia', models.BooleanField()),
                ('dostepnosc', models.BooleanField(default=True)),
                ('cena_za_dobe', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('adres', models.CharField(max_length=100)),
                ('wiek', models.PositiveIntegerField()),
                ('telefon', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Wypozyczenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wypozyczenia', models.DateField()),
                ('data_zwrotu', models.DateField()),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.auto')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.klient')),
            ],
        ),
    ]
